### ISSUE TITLE
Unable to Connect to Robot Client while Running Kinesthetic Demonstration

### ISSUE THREAD

**Issue by CarMan-W** [Stanford-ILIAD/lilac#1]
**Description:**
I encountered an issue while attempting to run the Kinesthetic Demonstration using the provided script. The error occurs during the execution of demonstrate.py and seems to be related to the connection with the robot client. Below is the traceback of the error:

```
[*] Starting Kinesthetic Demonstration Collection...
Traceback (most recent call last):
  File "scripts/demonstrate.py", line 55, in <module>
    demonstrate()
  File "scripts/demonstrate.py", line 39, in demonstrate
    env = FrankaEnv(do_kinesthetic=True)
  File "/home/sebolab/Desktop/Unlearning/lilac_org/lilac/robot/env.py", line 79, in __init__
    self.reset()
  File "/home/sebolab/Desktop/Unlearning/lilac_org/lilac/robot/env.py", line 138, in reset
    self.robot = RobotInterface(ip_address=self.franka_ip, enforce_version=False)
  File "/home/sebolab/anaconda3/envs/lilac/lib/python3.8/site-packages/polymetis/robot_interface.py", line 348, in __init__
    super().__init__(*args, **kwargs)
  File "/home/sebolab/anaconda3/envs/lilac/lib/python3.8/site-packages/polymetis/robot_interface.py", line 89, in __init__
    else self.grpc_connection.GetRobotClientMetadata(EMPTY)
  File "/home/sebolab/anaconda3/envs/lilac/lib/python3.8/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/sebolab/anaconda3/envs/lilac/lib/python3.8/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.16.0.2:50051: Failed to connect to remote host: FD Shutdown"
    debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.16.0.2:50051: Failed to connect to remote host: FD Shutdown {created_time:"2023-08-21T17:17:14.641537194-04:00", grpc_status:14}"
```

**Steps to Reproduce:**

    Install Polymetis and all required dependencies according to the provided installation process.
    Run the command: python scripts/demonstrate.py --task water-plant.

**Expected Behavior:**
The Kinesthetic Demonstration should run successfully without any connection issues with the robot client.

**Additional Information:**
I was able to successfully run the launch_robot.py script using the command launch_robot.py robot_client=franka_hardware under the same settings, which indicates that my setup is correct and the robot client can be initialized.
The only modification I made was changing the ip_address in "lilac/robot/env.py" to 172.16.0.2, which is the ip_address of the Panda Arm control box.

I would appreciate any assistance in resolving this issue and successfully running the Kinesthetic Demonstration. Thank you for your support!

**Comment by CarMan-W** [comment]
Issue resolved by first using NUC to start a server first with launch_robot.py, then use another PC to run the demonstrate.py with the ip_address set to the ip of NUC.
This page helped: https://github.com/AGI-Labs/franka_control

**Comment by CarMan-W** [comment]
Issue resolved by first using NUC to start a server first with launch_robot.py, then use another PC to run the demonstrate.py with the ip_address set to the ip of NUC.
This page helped: https://github.com/AGI-Labs/franka_control
